добавляет авторизация и регистрацию
twenty-forty-eight-kubiki/twenty-forty-eight pull request #11
Opened 2023-03-10 17:11 UTC by yulaivanova

### Какую задачу решаем
Добавляет Аутентификацию и Авторизацию

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-10 17:33 UTC, manshind requested changes

2023-03-10 17:33 UTC, manshind commented on packages/client/src/api/api.ts
> +      return contentType && contentType.indexOf("application/json") !== -1 ? response.json() : null;
Возможно не нужно отсеивать не json ответы. Может быть вы потом захотите файлы передавать, из за такой проверки вы не сможете так делать

2023-03-10 17:33 UTC, manshind commented on packages/client/src/api/authApi.ts
> +    return API.post<BodyInit, LoginRequestData>(`${BASE_URL}/auth/signin`, userData)
Префикс basePath можешь сразу в API добавить, чтобы везде не писать

2023-03-10 17:33 UTC, manshind commented on packages/client/src/api/authApi.ts
> +    return API.post<BodyInit, SignupRequestData>(`${BASE_URL}/auth/signup`, userData)
Почему ты в ответ засовываешь тип параметров запроса?

2023-03-10 17:33 UTC, manshind commented on packages/client/src/api/authApi.ts
> +    return API.post<BodyInit, []>(`${BASE_URL}/auth/logout`)
Что это за возвращаемый тип?

2023-03-10 17:33 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.scss
> +  &__link {
Почему это не в компоненте?

2023-03-10 17:33 UTC, manshind commented on packages/client/src/api/authApi.ts
> +type SignupRequestData = {
Советую вынести типы в отдельный файл. Иначе файл разрастется и с ним будет неудобно работать

2023-03-10 17:33 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +          if (apiHasError(response)) {
Странное поведение. Такое должно обрабатываться с помощью catch. Если ответ от сервера успешный, нехорошо возвращать в нем ошибку

2023-03-10 17:33 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +      authAPI.login(JSON.stringify(loginData))
Зачем тут стрингифай?

2023-03-10 17:33 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +              <Link to='/registration' className="login-form__link"> Sign up</Link>
В отдельный компонент

2023-03-10 17:33 UTC, manshind commented on packages/client/src/components/ProfileList/ProfileList.tsx
> +        if (apiHasError(response)) {
Не должно тут быть такого. Подробнее писал выше

2023-03-10 17:33 UTC, manshind commented on packages/client/src/components/RegisatrationForm/RegistrationForm.scss
> +  &__link {
В компонент

2023-03-10 17:33 UTC, manshind commented on packages/client/src/components/RegisatrationForm/RegistrationForm.scss
> +  &__error {
Советую так же сделать компонент ошибки

2023-03-10 17:33 UTC, manshind commented on packages/client/src/components/RegisatrationForm/RegistrationForm.tsx
> +      const userData = {
Укажи тип параметров запроса

2023-03-10 17:33 UTC, manshind commented on packages/client/src/components/RegisatrationForm/RegistrationForm.tsx
> +      authAPI.signup(JSON.stringify(userData))
Зачем стрингифай?

2023-03-10 17:33 UTC, manshind commented on packages/client/src/components/RegisatrationForm/RegistrationForm.tsx
> +          if (apiHasError(response)) {
Не должно быть тут

2023-03-10 17:33 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +      const loginData = {
Добавь тип

2023-03-11 09:12 UTC, yulaivanova commented on packages/client/src/api/api.ts
> +      return contentType && contentType.indexOf("application/json") !== -1 ? response.json() : null;
просто иногда приходит ответ "OK" строкой, и из-за этого появляется ошибка "OK" is not valid JSON, для этого добавила проверку, как тут лучше сделать тогда?

2023-03-11 09:31 UTC, yulaivanova commented on packages/client/src/api/authApi.ts
> +    return API.post<BodyInit, SignupRequestData>(`${BASE_URL}/auth/signup`, userData)
я очень запуталась с типизацией и наворотила всего, сейчас поправила
но все равно до конца не уверена, что правильно затипизировала все) посмотри, пожалуйста

2023-03-11 09:31 UTC, yulaivanova commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +      authAPI.login(JSON.stringify(loginData))
убрала

2023-03-11 10:31 UTC, manshind commented on packages/client/src/api/api.ts
> +      return contentType && contentType.indexOf("application/json") !== -1 ? response.json() : null;
Иногда это в каких случаях? Правильнее всего будет возвращать с сервера стандартизированый ответ в виде джсона. Если у вас нет доступа к серверу и ответ строкой приходит только в конкретных эндпоинтах, то стоит производить преобразование в каждом конкретном эндпоинте (у вас есть файл authApi, в котором описываются конкретные методы, вот в каждом нужно тогда делать либо response.json() либо еще какое нибудь преобразование, если требуется другое).

Либо же определить сопоставление заголовка content-type с конкретной обработкой ответа. Например для джсона - response.json(), для текста - response.text() (если такое есть) и тд. А после в файле api уже по контент тайпу обрабатывать, примерно как ты делаешь сейчас, но предусмотреть различные форматы ответа.

Можешь выбрать любой из второго или третьего варианта. Я бы остановился на третьем, это выглядит немного удобнее, так как не надо каждый раз писать одно и то же.

Получилось довольно много текста, если что то непонятно - пиши

2023-03-11 10:58 UTC, manshind commented on packages/client/src/api/api.ts
> +function request<T>(url: string, config: RequestInit = {}) {
Этот дженерик нигде не используется. Надо указать, что этот дженерик - возвращаемый тип.
То есть function request<{T}>(): Promise<{T}> {}
Фигурные скобки в дженерике не нужны, пришлось их поставить из за форматирования

2023-03-11 10:58 UTC, manshind commented on packages/client/src/api/api.ts
> +  get: (url: string) =>
Нужно добавить возвращаемый тип через дженерик

2023-03-11 10:58 UTC, manshind commented on packages/client/src/api/api.ts
> +  post: <T>(url: string, body?: T) =>
Нужно добавить еще возвращаемый тип через дженерик

2023-03-11 10:58 UTC, manshind commented on packages/client/src/api/api.ts
> +    request<T>(url, {
Тут должен быть не T

2023-03-11 10:58 UTC, manshind commented on packages/client/src/api/authApi.ts
> +    return API.post<LoginRequestData>('auth/signin', userData)
Еще для каждого метода нужно описать возвращаемый тип

2023-03-11 10:58 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +          if (response && response.reason) {
Не совсем поняла про то, что я писал. Я имел в виду, что в блоке then ошибки не обрабатываются, за это отвечает catch.
Почему ты вообще так решила сделать?

2023-03-11 10:58 UTC, manshind commented on packages/client/src/types/api.ts
> +export type SignupRequestData = {
Сделай файл api папкой, а внутри уже раздели на конкретные апи, по типу authApi и тд, в каждом файле будете описывать конкретные типы.

Иначе это потом все намешается и будет неудобно работать

2023-03-11 13:24 UTC, yulaivanova commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +          if (response && response.reason) {
так сделано, что если ответ не ок, то он отдает ответ типа {reason: 'описание ошибки, например, неверный пароль"}
мне в компонент уже приходит такой ответ, если не проверять response.reason, как понять что это ошибка пришла?

2023-03-11 13:28 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +          if (response && response.reason) {
В таком случае, чтобы избежать дублирования и соблюдать более удобный подход, можно в api.ts делать в then такую проверку и если она выполняется, делать Promise.reject(response.reason), ну или просто исключение бросить.

Так ты сможешь ошибку обрабатывать с помощью catch, а успех в then, как это и должно быть

2023-03-11 13:30 UTC, yulaivanova commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +          if (response && response.reason) {
для того, чтобы эту ошибку в форме отобразить

2023-03-11 13:33 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +          if (response && response.reason) {
Ну вот если сделаешь как описал в предыдущем комменте, ты сможешь реагировать на ошибку более правильно

2023-03-11 13:45 UTC, manshind commented on packages/client/src/api/authApi.ts
> +    return API.post<LoginRequestData, APIError>('auth/signin', userData)
В ответе на логин всегда будет ошибка приходить? Почему такой тип?

2023-03-11 13:45 UTC, manshind commented on packages/client/src/api/authApi.ts
> +  async logout(): Promise<any> {
Если не ожидаешь ответа, то лучше писать void. Избегай указания any

2023-03-11 13:45 UTC, manshind commented on packages/client/src/api/authApi.ts
> +  async signup(userData: SignupRequestData): Promise<signupResponse> {
Типы с большой буквы пиши

2023-03-11 13:45 UTC, manshind commented on packages/client/src/api/api.ts
> +        return null
response.text()

null тебе не отдаст ответ

2023-03-11 13:45 UTC, manshind commented on packages/client/src/types/api/authApi.ts
> +export type APIError = {
Это можно вынести в /types/api/shared

Такой тип может использоваться не только в auth

2023-03-11 14:30 UTC, yulaivanova commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +          if (response && response.reason) {
если это проверять в api.ts, в самом же компоненте все равно придется проверять что пришел объект c reason, чтобы установить этот текст в форму, не понимаю как по другому)

2023-03-11 14:44 UTC, yulaivanova commented on packages/client/src/api/authApi.ts
> +    return API.post<LoginRequestData, APIError>('auth/signin', userData)
не понимаю как указать что будет приходить либо ошибка(объект {reason: ''}), либо строка с ОК

2023-03-11 15:19 UTC, yulaivanova commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +          if (response && response.reason) {
кажется все-таки получилось)

2023-03-11 15:19 UTC, yulaivanova commented on packages/client/src/api/authApi.ts
> +    return API.post<LoginRequestData, APIError>('auth/signin', userData)
тут поправила

2023-03-11 16:03 UTC, manshind requested changes

2023-03-11 16:03 UTC, manshind commented on packages/client/src/components/ProfileList/ProfileList.tsx
> +          return Promise.reject()
Это надо сделать в api, иначе придется каждый раз так писать

2023-03-11 16:03 UTC, manshind commented on packages/client/src/components/ProfileList/ProfileList.tsx
> +      .catch(e => console.log('error', e))
У тебя уже есть логирование ошибки в api. Этот кусок кода не вызовется никогда, его можно просто убрать

2023-03-11 16:03 UTC, manshind commented on packages/client/src/api/authApi.ts
> +    return API.post<LoginRequestData, APIError>('auth/signin', userData)
Ошибка в типе промиса не указывается, в нем указывается только успешный ответ. Ошибку нужно писать в каждом catch. 
Если из промиса приходит строка, то это просто string

2023-03-11 16:03 UTC, manshind commented on packages/client/src/api/api.ts
> +      if (!response.ok) {
Если сервер отдаёт ошибку только с помощью отправки reason, то эта проверка не сработает.
response.ok будет true только когда код ответа 2хх.
Для начала надо понять, что для сервера считается ошибкой. Если в случае ошибки он пришлет код 200 и в теле reason, то надо указать условие, которое ты указывала раньше, то есть проверку на наличие reason.
Если код будет не 200, то скорее всего это условие вообще не нужно и промис самостоятельно перейдет в catch

2023-03-11 16:03 UTC, manshind commented on packages/client/src/api/api.ts
> +    .catch((error: Promise<APIError>) => {
Ошибка это не промис, это уже просто APIError

2023-03-11 16:03 UTC, manshind commented on packages/client/src/api/api.ts
> +    .catch((error: Promise<APIError>) => {
Этот catch не нужен, он и так пробросит ошибку дальше

2023-03-11 16:03 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +          response.then((error: APIError) => {
Это не промис, это уже обычная ошибка.
Старайся проверять работоспособность кода, который отдаешь на пр

2023-03-11 16:12 UTC, yulaivanova commented on packages/client/src/api/api.ts
> +      if (!response.ok) {
пока мы используем яндексовый свагер https://ya-praktikum.tech/api/v2/swagger/
там не приходит код 200 и поле reason, только в ошибке, когда не response.ok
могу оставить так как сейчас тогда?

2023-03-11 16:18 UTC, manshind commented on packages/client/src/api/api.ts
> +      if (!response.ok) {
А, да. Reason приходит не с 200 кодом, а fetch его все равно в then отправит. В таком случае твоя проверка верная

2023-03-11 16:27 UTC, yulaivanova commented on packages/client/src/api/api.ts
> +      if (!response.ok) {
еще немного подправила

2023-03-11 16:27 UTC, yulaivanova commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +          response.then((error: APIError) => {
все работало) я в catch промис отдавала, из-за этого тут все ок работало

2023-03-11 16:32 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +          response.then((error: APIError) => {
Сорри тогда, не заметил. Но в любом случае для данного кейса это переусложнение, отдавай в реджект обычную ошибку. Иначе с этим тяжело будет работать

2023-03-11 16:48 UTC, manshind approved these changes

2023-03-11 16:48 UTC, manshind commented on packages/client/src/api/api.ts
> +      if (data && data.reason) {
В целом и с этим жить можно, но есть момент.
Если вдруг будет ошибка с кодом 500, то твоя проверка не сработает, так как в сваггере для данного кода я не увидел reason.
И получается что твой код будет думать, что все прошло успешно.

Если делать сразу правильно, то скорее нужно сначала проверить на response.ok, потом проверить на reason, и если его нет, то возвращать какую то мета инфу из запроса, чтобы ошибка не потерялась.

2023-03-11 17:06 UTC, yulaivanova commented on packages/client/src/api/api.ts
> +      if (data && data.reason) {
а технически как правильно так сделать?
как в одном then сразу получить response.reason, сначала же мы должны response.json() сделать, а это будет промисом
не очень понимаю как технически реализовать это можно

2023-03-11 19:33 UTC, manshind commented on packages/client/src/api/api.ts
> +      if (data && data.reason) {
Ты можешь например в первом then возвращать не только response.json(), а сделать как response.json().then(data => [response, data]);

А затем в следующем then уже проверять на response.ok и возвращать нужные данные.


А вообще, советую не париться и использовать axios

2023-03-12 11:31 UTC, merged