KUBIK-28
twenty-forty-eight-kubiki/twenty-forty-eight pull request #13
Opened 2023-03-14 12:10 UTC by ivee7

### Какую задачу решаем
- Добавление redux, redux-thunk, redux-хуки;
- Интеграция api, redux и routing'а

### Скриншоты/видяшка (если есть)

### TBD (если есть)
- создать архитектуру хранения и работы с данными с сервера;

2023-03-15 12:00 UTC, manshind requested changes

2023-03-15 12:00 UTC, manshind commented on packages/client/package.json
> +    "@types/react-redux": "^7.1.25",
вынеси типы в devDependencies. Они не попадают в итоговую сборку

2023-03-15 12:00 UTC, manshind commented on packages/client/src/components/ProfileList/ProfileList.tsx
> +    history.push(RoutePath.root)
лучше делать это в then, иначе в случае ошибки роут тоже изменится, а логаута не произойдет, для пользователя будет непонятно

2023-03-15 12:00 UTC, manshind commented on packages/client/src/main.tsx
> +const application = (
это компонент, а компоненты называют с большой буквы

2023-03-15 12:00 UTC, manshind commented on packages/client/src/router/AppRouter.tsx
> +    dispatch(fetchUser())
роутер не должен отвечать за получение юзера, он отвечает только за роутинг. Лучше fetchUser делать в App или в каком нибудь другом корневом месте

2023-03-15 12:00 UTC, manshind commented on packages/client/src/router/AppRouter.tsx
> +      {isAuth ? <Route path={HEADER_PATHS} component={Header} /> : null}
хедер уже в лейауте рисуется, либо оттуда его вынести и оставить здесь, либо обернуть каждую страницу в лейаут
Второй вариант выглядит более правильным

2023-03-15 12:00 UTC, manshind commented on packages/client/src/router/AppRouter.tsx
> +      <PrivateRoute
почему это не в конфиге со всеми остальными роутами?

2023-03-15 12:00 UTC, manshind commented on packages/client/src/router/RoutePath.ts
> +  root = '/',
в енамах принято либо называть с большой буквы либо капсом.
Тем более у вас уже есть енамы, где все называется с большой буквы.
Не надо смешивать подходы, используйте один во всем проекте

2023-03-15 12:00 UTC, manshind commented on packages/client/src/store/store.ts
> +export type RootState = ReturnType<typeof rootReducer>
вынеси это в store.types

2023-03-16 11:14 UTC, ivee7 commented on packages/client/package.json
> +    "@types/react-redux": "^7.1.25",
вынес

2023-03-16 11:15 UTC, ivee7 commented on packages/client/src/components/ProfileList/ProfileList.tsx
> +    history.push(RoutePath.root)
исправил

2023-03-16 11:17 UTC, ivee7 commented on packages/client/src/main.tsx
> +const application = (
изменил

2023-03-16 11:38 UTC, ivee7 commented on packages/client/src/router/AppRouter.tsx
> +      {isAuth ? <Route path={HEADER_PATHS} component={Header} /> : null}
не можем понять до конца с тем, как настроить routing и авторизацию, динамический показ разных лейаутов(

2023-03-16 12:34 UTC, manshind commented on packages/client/src/router/AppRouter.tsx
> +      {isAuth ? <Route path={HEADER_PATHS} component={Header} /> : null}
не совсем понял вопрос.
Опиши ситуацию чуть более детально, а я постараюсь помочь

2023-03-16 12:36 UTC, manshind commented on packages/client/src/store/reducers/AuthSlice.ts
> +        state.authorizationStatus = false
зачем это поле? инфы в виде статуса, ошибки и data не хватает?

2023-03-16 12:39 UTC, ivee7 commented on packages/client/src/store/reducers/AuthSlice.ts
> +        state.authorizationStatus = false
уберу

2023-03-16 12:41 UTC, ivee7 commented on packages/client/src/router/AppRouter.tsx
> +      {isAuth ? <Route path={HEADER_PATHS} component={Header} /> : null}
когда авторизован, есть возможность перейти на страницу логина (такого не должно быть). Четко разделить private route и public routes (login, registration)

2023-03-16 12:48 UTC, manshind commented on packages/client/src/router/AppRouter.tsx
> +      {isAuth ? <Route path={HEADER_PATHS} component={Header} /> : null}
Для private роутов у вас есть отдельный компонент, public роуты - это все остальные.
То есть, если вы переходите на страницу через PrivateRoute, должна быть проверка на юзера, и если юзера нет, то кидать на страницу логина. Если вы переходите через обычный Route, то никаких проверок не будет и у вас просто отрисуется компонент.
А когда у вас есть юзер и вы пытаетесь перейти на страницу логина, вы можете просто делать редирект на главную страницу или еще куда нибудь (просто сделать эту проверку на самой странице логина или сделать отдельный компонент роута, который будет проверять наличие юзера и если он есть перенаправлять на главную, по аналогии с вашим PrivateRoute).

2023-03-16 12:53 UTC, manshind commented on packages/client/src/router/AppRouter.tsx
> +  if (!isAuthChecked) {
лучше проверку на существование юзера и состояние загрузки тоже в App делать

2023-03-18 11:18 UTC, manshind approved these changes

2023-03-18 11:18 UTC, manshind commented on packages/client/src/store/reducers/AuthSlice.ts
> +export const fetchUser = createAsyncThunk<UserInfoResponse, undefined>(
Лучше выноси санки в отдельный файл, иначе этот станет большим и неудобным

2023-03-18 11:18 UTC, manshind commented on packages/client/src/main.tsx
> +store.dispatch(fetchUser())
Так делать не надо, запросы стоит делать строго внутри компонентов

2023-03-18 11:18 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +          history.push(RoutePath.Login)
Почему перенаправляешь снова на логин?

2023-03-18 12:20 UTC, yulaivanova commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +          history.push(RoutePath.Login)
это ошибка, поправила

2023-03-18 12:33 UTC, merged