kubik-19 - Страница входа и регистрации
twenty-forty-eight-kubiki/twenty-forty-eight pull request #2
Opened 2023-02-28 10:48 UTC by hellencheetah

### Какую задачу решаем
Сверстала страницы авторизации и регистрации
Создала класс для валидации и добавила валидацию полей

2023-03-01 00:57 UTC, ivee7 commented on packages/client/src/App.tsx
импорты стараемся делать в едином стиле: одинаковые кавычки)

2023-03-01 12:44 UTC, yulaivanova approved these changes

2023-03-01 12:55 UTC, manshind reviewed
структура дирректорий для компонентов выглядит довольно разбросанной.
Я бы предложил сделать следующее:
/ui
  /pages - лежат все страницы
  /shared - лежат все базовые переиспользуемые компоненты
  /features - лежат конкретные компоненты из страниц

Подобная структура больше отражает суть происходящего, а у вас сейчас одни и те же сущности разбросаны по разным папкам

2023-03-01 12:55 UTC, manshind commented on packages/client/src/App.tsx
> +import LoginPage from './pages/LoginPage/LoginPage';
Некритично. Старайтесь использовать именнованные импорты/экспорты вместо дефолтных, с ними будет удобнее работать в дальнейшем.

2023-03-01 12:55 UTC, manshind commented on packages/client/src/App.tsx
> +    return <div className="App">
Пользуйтесь линтером. Он поможет сделать код более читаемым и понятным остальным членам команды

2023-03-01 12:55 UTC, manshind commented on packages/client/src/assets/scss/_generic.scss
>  button {
подобные стили стоит делать в конкретных компонентах кнопок

2023-03-01 12:55 UTC, manshind commented on packages/client/src/assets/scss/_generic.scss
>  input {
подобные стили стоит делать в конкретных компонентах инпутов

2023-03-01 12:55 UTC, manshind commented on packages/client/src/assets/scss/_generic.scss
>  ul,
подобные стили стоит делать в конкретных компонентах списков

2023-03-01 12:55 UTC, manshind commented on packages/client/src/assets/scss/_generic.scss
> +.base-link {
подобные стили стоит делать в конкретных компонентах ссылок

2023-03-01 12:55 UTC, manshind commented on packages/client/src/assets/scss/_generic.scss
> +.container {
советую выносить это в отдельные компоненты. Иначе этот файл разрастется и с ним будет неудобно работать

2023-03-01 12:55 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.scss
> +  height: 587px;
Зачем ограничиваешь высоту? При изменении верстки она принесет проблем, а этот блок и так будет расширяться контентом

2023-03-01 12:55 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +import './LoginForm.scss'
импорты стилей лучше делать в конце всех остальных импортов, чтобы была возможность перебивать стили используемых компонентов.

2023-03-01 12:55 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +              Don't have an account? <a className="base-link">Sign up</a>
ссылку лучше сделать компонентом

2023-03-01 12:55 UTC, manshind commented on packages/client/src/types/form.ts
> +export enum FormFields {
выглядит так, будто этот енам должен находиться рядом с самой формой, а не глобально, так как в вашем приложении может быть много форм и подобное вынесение может принести конфликты и недопонимания

либо же разделить этот енам на конкретные формы, например LoginFormFields и RegistrationFormFields

2023-03-01 12:55 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +    email: {
почему не используется FormFields?

2023-03-01 12:55 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +    password: {
почему не используется FormFields?

2023-03-01 12:55 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +    email: null,
почему не используется FormFields?

2023-03-01 12:55 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +    password: null,
почему не используется FormFields?

2023-03-01 12:55 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +  const easyValidator = new EasyValidator(schema)
возможно стоит вынести это объявление в useRef, иначе эта конструкция будет вызываться на каждый рендер компонента. А если в EasyValidator есть какое либо внутреннее состояние, то он не будет работать корректно

2023-03-01 12:55 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +    // @ts-ignore
игнорить ошибки ts не надо, лучше везде обвязать все правильными типами

2023-03-01 12:55 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +    setEmail((e.target as HTMLInputElement).value)
подозреваю, что FormEvent принимает дженерик, в который можно сунуть HTMLInputElement, и тогда as HTMLInputElement будет не нужен

2023-03-01 12:55 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +  const resetError = (type: string) => {
почему это стринга, если поля этой формы представлены конкретным енамом? Лучше использовать его в качестве типа

2023-03-01 12:55 UTC, manshind commented on packages/client/src/components/RegisatrationForm/RegistrationForm.scss
> +  height: 807px;
не надо ограничивать высоту

2023-03-01 12:55 UTC, manshind commented on packages/client/src/ui/GuiButton/GuiButton.tsx
> +  const btnClass = () => {
название не соответсвует тому, что это функция. Название функции должно указывать на действие. А btnClass лучше сделать константой

2023-03-01 12:55 UTC, manshind commented on packages/client/src/ui/GuiButton/GuiButton.tsx
> +    <button className={btnClass()} type={type} onClick={() => onClick}>
onClick={() => onClick} не будет работать. Либо onClick={onClick}, либо onClick={() => onClick()}

2023-03-01 12:55 UTC, manshind commented on packages/client/src/ui/GuiInput/GuiInput.tsx
> +  name: FormFields
такое ограничение имени делает компонент слабо переиспользуемым, лучше проп name вообще убрать

2023-03-01 12:55 UTC, manshind commented on packages/client/src/ui/GuiInput/GuiInput.tsx
> +          onBlur={() => onBlur(props.name)}
name лучше указывать в компоненте, который использует GuiInput, это сделает его более переиспользуемым

2023-03-01 12:55 UTC, manshind commented on packages/client/src/ui/GuiInput/GuiInput.tsx
> +      <div v-if={props.error} className="gui-input-error">
v-if={props.error} в реакте нет, нужно использовать {!!props.error && ....}

2023-03-01 12:55 UTC, manshind commented on packages/client/src/helpers/validators.ts
> +    if (value !== form.password) {
нехорошо завязываться на конкретное имя password, в разных формах оно может называться по разному

2023-03-01 12:55 UTC, manshind commented on packages/client/src/helpers/easy-validator.ts
> +      // @ts-ignore
не надо игнорить ошибки тс, обвяжи типами

2023-03-01 15:23 UTC, hellencheetah commented on packages/client/src/assets/scss/_generic.scss
>  button {
Не мое, уберу

2023-03-01 15:24 UTC, hellencheetah commented on packages/client/src/assets/scss/_generic.scss
>  input {
уберу

2023-03-01 15:24 UTC, hellencheetah commented on packages/client/src/assets/scss/_generic.scss
>  ul,
уберу

2023-03-01 15:26 UTC, hellencheetah commented on packages/client/src/ui/GuiInput/GuiInput.tsx
> +  name: FormFields
да, но конкретно в этом проекте это способ, которым я пытаюсь уменьшить количество обработчиков, а без этого поля придется для каждого инпута свой обработчик писать, чтобы сбросить ошибку.

если как-то по-другому можно сделать - я бы хотела знать как)

2023-03-01 15:27 UTC, hellencheetah commented on packages/client/src/ui/GuiInput/GuiInput.tsx
> +      <div v-if={props.error} className="gui-input-error">
упс, привычка vue-шная, уберу

2023-03-01 15:31 UTC, hellencheetah commented on packages/client/src/helpers/validators.ts
> +    if (value !== form.password) {
он не задумывался универсальным, но ок, прокину еще одно поле в конфиг :)

2023-03-01 15:34 UTC, hellencheetah commented on packages/client/src/App.tsx
> +    return <div className="App">
А что тут не так?

2023-03-01 15:35 UTC, manshind commented on packages/client/src/ui/GuiInput/GuiInput.tsx
> +  name: FormFields
количество обработчиков никак не меняется, просто ты прокидывание name выносишь в обработчик компонента, находящегося на уровень выше

2023-03-01 15:40 UTC, manshind commented on packages/client/src/App.tsx
> +    return <div className="App">
переносы строк кривые

2023-03-01 20:50 UTC, manshind requested changes
Пробегись по всем комментариям.
GitHub большую часть из того что я писал схлопнул, видимо чтобы не занимать место на странице, и скорее всего ты их не увидела

2023-03-01 20:50 UTC, manshind commented on packages/client/src/types/form.ts
> +export type Form = Record<string, string | null> | Record<string, never>
какой то бесполезный тип в таком виде, лучше перечисли конкретные поля, тогда от него будет польза

2023-03-01 20:50 UTC, manshind commented on packages/client/src/assets/scss/_generic.scss
>  a {
почему оставила?

2023-03-02 13:14 UTC, manshind approved these changes
Основные комменты вроде поправила. Осталась пара моментов, пройди по ним.
Ставлю заранее аппрув

2023-03-02 13:14 UTC, manshind commented on packages/client/src/types/form.ts
> +} | Record<string, never>
Некритично. Record<string, never> не нужен

2023-03-02 13:14 UTC, manshind commented on packages/client/src/types/form.ts
> +} | Record<string, never>
Некритично. Record<string, never> не нужен

2023-03-02 13:14 UTC, manshind commented on packages/client/src/ui/GuiButton/GuiButton.tsx
> +    <button className={`gui-button ${className}`} type={type} onClick={() => onClick}>
предыдущим способом ты делала более правильно, щас у тебя часто будет лишний пробел в классе

2023-03-02 13:14 UTC, manshind commented on packages/client/src/ui/GuiLink/GuiLink.tsx
> +
используйте линтер. Желательно перед каждым пр прогонять его для всех файлов

2023-03-02 13:14 UTC, manshind commented on packages/client/src/ui/GuiButton/GuiButton.tsx
> +    <button className={btnClass()} type={type} onClick={() => onClick}>
> onClick={() => onClick} не будет работать. Либо onClick={onClick}, либо onClick={() => onClick()}

!!!

2023-03-03 16:33 UTC, merged