добавляет хранение состояния игры в стор
twenty-forty-eight-kubiki/twenty-forty-eight pull request #20
Opened 2023-03-26 15:57 UTC by yulaivanova

### Какую задачу решаем
добавляет хранение состояния игры в стор, делает рестарт игры по кнопке контрола

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-26 16:04 UTC, manshind requested changes

2023-03-26 16:04 UTC, manshind commented on packages/client/src/store/reducers/GameSlice.ts
> +      const { countTiles } = useGameConfig();
Хуки должны вызываться исключительно внутри компонентов

2023-03-26 16:04 UTC, manshind commented on packages/client/src/store/reducers/GameSlice.ts
> +import { useGameConfig } from '../../components/Game/hooks/useGameConfig';
Лучше не делать такое направление зависимости. Стора не должна импортировать что либо из компонентов, перенеси утилиты в другое место, например в корневой utils, иначе могут быть циклические зависимости

2023-03-26 16:04 UTC, manshind commented on packages/client/src/store/reducers/GameSlice.ts
> +} from '../../components/Game/helpers/board';
Аналогично предыдущему комменту

2023-03-26 16:04 UTC, manshind commented on packages/client/src/store/store.types.ts
> +import { Board } from '../components/Game/common/types';
Аналогично предыдущему комменту

2023-03-26 20:00 UTC, manshind approved these changes

2023-03-26 20:00 UTC, manshind commented on packages/client/src/store/reducers/GameSlice.ts
> +    setTileSize: state => {
Это выглядит как селектор, тут вся логика завязана на данных из сторы

2023-03-27 08:10 UTC, yulaivanova commented on packages/client/src/store/reducers/GameSlice.ts
> +    setTileSize: state => {
пернесла

2023-03-27 08:10 UTC, merged