Kubik 48 Настраивает Express для Server Side Rendering
twenty-forty-eight-kubiki/twenty-forty-eight pull request #26
Opened 2023-04-07 14:30 UTC by yulaivanova

### Какую задачу решаем
Настраивает Express для Server Side Rendering

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-07 15:45 UTC, manshind requested changes

2023-04-07 15:45 UTC, manshind commented on packages/client/src/helpers/fullscreen.ts
> +// const fullscreenDocument = document as FullscreenDocument;
Если не нужно - удали

2023-04-07 15:45 UTC, manshind commented on packages/client/src/helpers/fullscreen.ts
> +    (document as FullscreenDocument).exitFullscreen();
Зачем?

2023-04-07 15:45 UTC, manshind commented on packages/client/ssr.tsx
> +      <App />
Почему нет BrowserRouter? Почему не используется один компонент и тут и на клиенте?

2023-04-07 15:45 UTC, manshind commented on packages/server/package.json
> +    "build-client": "cd ../client && npm run build",
Выглядит так, будто это не должно быть тут, у вас есть корневой package.json для таких вещей

2023-04-08 09:05 UTC, yulaivanova commented on packages/client/src/helpers/fullscreen.ts
> +    (document as FullscreenDocument).exitFullscreen();
если вернуть как раньше и вынести в отдельную переменную(const fullscreenDocument = document as FullscreenDocument), то появляется такая ошибка при сборке - https://skr.sh/sJFzw8uhxbl
не понимаю как ее убрать

2023-04-08 09:08 UTC, yulaivanova commented on packages/client/ssr.tsx
> +      <App />
если добавить роутер, то появляется такая ошибка - https://skr.sh/sJFiS9GJTEZ
тут тоже не знаю как это поправить
у нас есть отдельная задача на добавление роутера в ssr, видимо в ней получится поправить

2023-04-08 09:10 UTC, yulaivanova commented on packages/server/package.json
> +    "build-client": "cd ../client && npm run build",
@PlehanovEvgeniy можешь, пожалуйста, глянуть этот коммент

2023-04-08 10:45 UTC, manshind commented on packages/client/src/helpers/fullscreen.ts
> +    (document as FullscreenDocument).exitFullscreen();
Потому что на сервера во время ssr нет документа. Можно выносить в константу не в файле, а в самой функции. Это исправит проблему

2023-04-08 10:46 UTC, manshind commented on packages/client/ssr.tsx
> +      <App />
Пробовала гуглить?
Уверен ответ на этот вопрос есть. Скорее всего можно использовать другой роутер, не браузерный

2023-04-08 12:17 UTC, yulaivanova commented on packages/client/ssr.tsx
> +      <App />
Заменила на Static Router, тогда все окей

2023-04-08 12:20 UTC, yulaivanova commented on packages/server/package.json
> +    "build-client": "cd ../client && npm run build",
@manshind то есть нужно перенести это в корневой json?

2023-04-10 12:04 UTC, PlehanovEvgeniy commented on packages/server/package.json
> +    "build-client": "cd ../client && npm run build",
@manshind что бы сбилдить вместе с клиентом, и что бы работало нужно же прокинуть ему точку входа, или вообще на сервере не нужен фронт? 

просто так я могу из любого пэкейджа запустить, если не указать то сборка на сервере  не будем иметь смысла, тк ничего не отрисуется

2023-04-10 12:24 UTC, manshind commented on packages/server/package.json
> +    "build-client": "cd ../client && npm run build",
Как я понял тут ваша задача запустить одновременно и фронт и сервер.
В таком случае вы определяете в пекедже фронта скрипт запуска фронта, а в пекедже сервера - скрипт запуска сервера.
После этого в корневом пекедже вы описываете единый скрипт, который запускает и клиент и сервер.
Насколько я помню, ваша утилита которая помогает вам работать с монорепой, умеет это делать удобно.
То есть основная суть - запуск нескольких пекеджей лучше делать из корня

2023-04-10 14:21 UTC, PlehanovEvgeniy commented on packages/server/package.json
> +    "build-client": "cd ../client && npm run build",
Хорошо, понял, Спасибо

2023-04-18 16:16 UTC, manshind approved these changes

2023-04-19 10:28 UTC, merged