Добавляет OAuth авторизацию
twenty-forty-eight-kubiki/twenty-forty-eight pull request #32
Opened 2023-04-21 16:27 UTC by yulaivanova

### Какую задачу решаем
Добавляет OAuth авторизацию

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-21 16:39 UTC, manshind requested changes

2023-04-21 16:39 UTC, manshind commented on packages/client/src/constants/index.ts
> +export const OAUTH_REDIRECT_URI = 'http://localhost:3000/';
Это на проде не будет работать.
Нужно в зависимости от окружения настраивать или брать из location

2023-04-21 16:39 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +        `https://oauth.yandex.ru/authorize?response_type=code&client_id=${response.service_id}&redirect_uri=${OAUTH_REDIRECT_URI}`
Советую вынести это в константу или лучше даже в какую нибудь функцию хелпер

2023-04-21 16:39 UTC, manshind commented on packages/client/src/api/oathApi.ts
> +    const urlWithQueries = `${qs.stringify(queriesData)}`;
Название плохое, это не url

2023-04-21 16:39 UTC, manshind commented on packages/client/src/App.tsx
>      dispatch(fetchUser());
Щас запрос на фетч может лететь два раза. Точно нужно такое поведение?

2023-04-21 16:39 UTC, manshind commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +    oathAPI.getServiceID(redirect).then(response => {
Зачем этому запросу нужен путь для редиректа? Он же указывается в ссылке ниже.

2023-04-22 10:51 UTC, yulaivanova commented on packages/client/src/App.tsx
>      dispatch(fetchUser());
если убрать этот запрос, и добавить его в это условие, например, [так](https://skr.sh/sJTEOvp13EF) , то иногда падает [такая](https://skr.sh/sJTT0f2yjbA) ошибка при попытке залогиниться через яндекс и приложение наглухо зависает, можешь, пожалуйста,подсказать как тут лучше это сделать, чтобы такого избежать

2023-04-22 10:51 UTC, yulaivanova commented on packages/client/src/components/LoginForm/LoginForm.tsx
> +    oathAPI.getServiceID(redirect).then(response => {
убрала

2023-04-22 11:01 UTC, manshind commented on packages/client/src/App.tsx
>      dispatch(fetchUser());
Нужно больше инфы по ошибке. Пока непонятно с чем может быть проблема

2023-04-22 12:23 UTC, yulaivanova commented on packages/client/src/App.tsx
>      dispatch(fetchUser());
не понимаю в чем дело, почистила у себя кэш, добавила заголовки для post 'Access-Control-Allow-Origin': '*', и убрала лишнее условие [здесь](https://skr.sh/sJTD6hItLx0), вроде как перестало воспроизводиться

2023-04-22 12:31 UTC, manshind approved these changes

2023-04-22 12:42 UTC, merged