Kubik 17 - страница профиля/настроек профиля
twenty-forty-eight-kubiki/twenty-forty-eight pull request #4
Opened 2023-03-01 12:47 UTC by yulaivanova

### Какую задачу решаем

Сверстаны страница профиля, настроек профиля и модальное окно с загрузкой аватарки (на странице настроек профиля)

2023-03-01 13:06 UTC, manshind reviewed
Слей сначала https://github.com/twenty-forty-eight-kubiki/twenty-forty-eight/pull/2
Тут большая часть изменений дублируется

2023-03-02 08:41 UTC, yulaivanova commented
> Слей сначала #2 Тут большая часть изменений дублируется

слила 19 ветку себе и внесла правки у себя

2023-03-02 12:58 UTC, manshind commented
> > Слей сначала #2 Тут большая часть изменений дублируется
> 
> слила 19 ветку себе и внесла правки у себя

Изменения все равно отображаются. Посмотрю этот пр после слияния 19

2023-03-03 17:09 UTC, yulaivanova commented
> 
слили)

2023-03-04 17:51 UTC, manshind commented
> > 
> 
> слили)
> 
> 

Сделай git rebase от sprint_5, или мердж sprint_5 в свою ветку.

Тут показываются изменения у файлов, которые я уже смотрел, и они влиты. Так очень тяжело смотреть, поэтому попробуй сделать, что написал выше

2023-03-05 09:10 UTC, yulaivanova commented
> У тебя конфликты, тут показываются изменения у файлов, которые я уже смотрел, и они влиты. Так очень тяжело смотреть, поэтому попробуй сделать, что написал выше

смержила sprint_5 в свою ветку

2023-03-05 13:22 UTC, manshind requested changes
Файл user-icon лучше скачивать как svg файл, будет весить меньше и качество будет нормальное.
И его стоит сунуть в /src/assets/icons, чтобы можно было использовать импорт с помощью сборщика.

2023-03-05 13:22 UTC, manshind commented on packages/client/src/assets/scss/_generic.scss
> +.base-link {
должно быть в компоненте ссылки

2023-03-05 13:22 UTC, manshind commented on packages/client/src/assets/scss/_generic.scss
> +.visually-hidden {
лучше тоже вынести в отдельный компонент

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/FileModal/FileModal.scss
> +  form {
не завязывайся в стилях на элементы, делай через классы, иначе, когда поменяется верстка, придется править и стили

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/FileModal/FileModal.tsx
> +import './FileModal.scss'
импорт стилей надо в конце всех импортов, иначе не сможешь перебить стили например, GuiButton, так как он ипортируется после твоих стилей

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/FileModal/FileModal.tsx
> +    ;(fileLabel.current as HTMLElement).textContent = file.name
прогоняй линтер перед отправкой пр

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/FileModal/FileModal.tsx
> +    const file = (e.target as HTMLFormElement).files[0]
HTMLFormElement нужно сунуть в дженерик FormEvent

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/FileModal/FileModal.tsx
> +      ;(fileError.current as HTMLElement).textContent = 'Add file'
так делать не надо, реакт как раз и нужен, чтобы обновлять твою отрисовку. Это нужно обновлять через jsx

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/FileModal/FileModal.tsx
> +    ;(fileError.current as HTMLElement).textContent = ''
так не надо, описал выше

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/Modal/Modal.tsx
> +const Modal: Props = ({ isVisible = false, content, onClose }) => {
неправильное название типа, это не Props, это компонент

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/Modal/Modal.tsx
> +  React.useEffect(() => {
Некритично. Можно сделать импрот useEffect из реакта, зачем лишний раз так писать

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/Modal/Modal.tsx
> +  })
не забывай про зависимости, иначе будет вызываться какждый раз

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/Modal/Modal.tsx
> +  return !isVisible ? null : (
подобная инверсия условий делает код менее читаемым. Лучше вынеси условие выше:

if (!isVisble) {
   return null;
}

или 

return isVisible ? {jsx} : null

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/ProfileForm/ProfileForm.tsx
> +import '../Modal/Modal.scss'
стили модалки должны подключаться в модалке

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/ProfileForm/ProfileForm.tsx
> +import '../ProfileList/ProfileList.scss'
импорт стилей в конце

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/ProfileForm/ProfileForm.tsx
> +    setPassword((e.target as HTMLInputElement).value)
передавай тип через дженерик

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/ProfileForm/ProfileForm.tsx
> +  const resetError = (fieldName: string) => {
у тебя есть конкретный перечень филдов, используй его для типов

2023-03-05 13:22 UTC, manshind commented on packages/client/src/components/ProfileList/ProfileList.tsx
> +const ProfileList: Props = props => {
неправильное имя типа, писал чуть подробнее выше

2023-03-06 12:48 UTC, yulaivanova commented on packages/client/src/components/ProfileForm/ProfileForm.tsx
> +    setPassword((e.target as HTMLInputElement).value)
не понимаю, как именно тут через дженерик передавать тип

2023-03-06 13:16 UTC, yulaivanova commented on packages/client/src/components/Modal/Modal.tsx
> +  })
что тут имеется в виду под зависимостями?

2023-03-06 14:00 UTC, yulaivanova commented on packages/client/src/components/ProfileForm/ProfileForm.tsx
> +    setPassword((e.target as HTMLInputElement).value)
вроде как поняла как сделать, посмотришь, пожалуйста, так ли сделала)

2023-03-06 17:25 UTC, manshind commented on packages/client/src/components/Modal/Modal.tsx
> +  })
Массив зависимостей вторым аргументом. Он отвечает за то, когда эффект будет вызываться. Сейчас он у тебя вызывается всегда, что не есть хорошо

2023-03-06 17:36 UTC, manshind approved these changes
Молодец, грамотно все исправляешь. 
Ставлю заранее аппрув, но перед тем как заливать, поправь пару коментов, что остались

2023-03-06 17:36 UTC, manshind commented on packages/client/src/components/ProfileForm/ProfileForm.tsx
> +  const [avatar] = useState('icons/user-icon.svg')
Тут стейт лишний, это можно получить через импорт. А чтобы пути автоматически генерировались, стоит вынести иконку в /src/assets/icons, как я писал выше

2023-03-07 13:46 UTC, merged