Логика игры
twenty-forty-eight-kubiki/twenty-forty-eight pull request #5
Opened 2023-03-02 15:22 UTC by PlehanovEvgeniy

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-02 21:17 UTC, manshind requested changes
В целом очень хорошо структурированный код. Молодец!

2023-03-02 21:17 UTC, manshind commented on packages/client/src/App.css
> +body {
подобные стили лучше писать в index.scss

2023-03-02 21:17 UTC, manshind commented on packages/client/src/App.css
> +body {
замени css файл на scss

2023-03-02 21:17 UTC, manshind commented on packages/client/src/App.tsx
> +import './App.css';
советую делать импорт стилей после всех остальных импортов, чтобы иметь возможность перебивать стили импортируемых компонентов

2023-03-02 21:17 UTC, manshind commented on packages/client/src/hooks/useGameValue.tsx
> +export const useGameValue = () => {
почему это находится не в компоненте Game?

2023-03-02 21:17 UTC, manshind commented on packages/client/src/hooks/useGameValue.tsx
> +export const useGameValue = () => {
не очень понятное название, я бы назвал useGameConfig. Оно лучше отражает суть этого кода

2023-03-02 21:17 UTC, manshind commented on packages/client/src/hooks/useGameValue.tsx
> +export const useGameValue = () => {
Некритично. Вообще, хуки это то, что вызывает другие хуки. Это выглядит как обычная функция-хелпер

2023-03-02 21:17 UTC, manshind commented on packages/client/src/pages/GamePage/GamePage.tsx
> +import './GamePage.scss'
делай импорты стилей после импорта компонентов, иначе ты в них не сможешь перебить стили компонента Board, когда это понадобится

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/common/allias.ts
> +export type Board = number[][];
не очень понятное имя файла. Почему allias?

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/helpers/random.ts
> +export const randomInt = (min: number, max: number) => {
функция должна описывать действие. Сейчас название больше похоже на константу. Назови getRandomInt

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/helpers/movement.ts
> +    board[newX][newY] = board[x][y]
старайся делать такие функции чистыми, то есть чтобы они не изменяли внешнее состояние. Сейчас ты напрямую меняешь board, это в дальнейшем может принести большое количество проблем и неочевидных багов. Надо создавать копию board, менять ее, а потом возвращать новый board. Или использовать immer.js

Это касается всех твоих хелперов

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Tile/Tile.tsx
> +      <RoundedRectangle x={x} y={y} width={tileSize} height={tileSize} radius={5}
перед тем, как отдавать пр, прогоняй линтер для всех файлов

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Text/Text.tsx
> +    context.font = 'bold 75px serif';
так лучше не делать. Реакт не гарантирует, что в момент вызова компонента будет доступ к dom-элементам, поэтому такие вещи надо делать в useLayoutEffect или в useEffect

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/RoundedRectangle/RoundedRectangle.tsx
> +      context.fillStyle = color
так лучше не делать. Реакт не гарантирует, что в момент вызова компонента будет доступ к dom-элементам, поэтому такие вещи надо делать в useLayoutEffect или в useEffect

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Grid/Grid.tsx
> +      {[...Array(countTiles * countTiles).keys()].map((qwe, index) => {
что такое qwe? либо давай осознанные имена, либо назови "_", если не используется

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Grid/Grid.tsx
> +        row = row + 15 + tileSize;
число 15 вынеси в константу, не допускай в коде непонятных чисел

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Board/Board.tsx
> +  const [board, setBoard] = useState(Array(countTiles).fill(1).map(() => Array(countTiles).fill(0)))
вынеси это в хелпер getInitialBoard

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Board/Board.tsx
> +            setBoard([...randomNewTile(board)])
так делать очень опасно из за ассинхронности обновления стейта реакта. Тем более в большинстве версий реакта это вызовет две перерисовки.
Тут нужно сначала провести манипуляции с доской, а потом делать единый сетСтейт. Тем более деструктуризация тут бесполезна, ее надо выносить в эти хелперы.

Это касается всех подобных мест ниже

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Board/Board.tsx
> +    const startBoard = resetBoard(board)
вынеси это в хелпер initializeBoard

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Board/Board.tsx
> +    if (isGameEnd(board)) {
советую вынести это в хелпер checkBoardStatus. Потом тут еще может быть добавлена обработка состояния проигрыша или еще чего нибудь, функция может разрастись

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Board/Board.tsx
> +      setBoard([...resetBoard(board)])
делать каждый раз деструктуризацию плохо, это запросто может привести к багам, если кто то случайно забудет ее сделать, то этот эффект не сработает. Поэтому надо создавать новый клон доски в хелперах (писал об этом ниже)

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Board/Board.tsx
> +    const directionControls = (event: any) => {
вынеси это в хелпер handleMove (или как нибудь по другому можно назвать). Функция очень большая, лучше держать ее вне компонента

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Context/Context.tsx
> +  dpr: number;
что такое dpr? давай более понятные и полные названия

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Context/Context.tsx
> +    // @ts-ignore
не надо игнорить ошибки тс, надо их исправлять

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Context/Context.tsx
> +    context.clearRect(0, 0, actualWidth, actualHeight)
не делай подобных вещей в теле компонента. Это не будет правильно работать. Нужно выносить в useEffect или useLayoutEffect

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Context/Context.tsx
> +    context.clearRect(0, 0, actualWidth, actualHeight)
уверен, что очисткой должен заниматься этот компонент? У тебя то же самое происходит в Board

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Context/Context.tsx
> +  const [context, setContext] = useState<CanvasRenderingContext2D>()
не вижу смысла выносить это в стейт, это можно сделать обычной константой, так оно только усложняет код.

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Context/Context.tsx
> +        canvasContext.scale(dpr, dpr)
учитывая предыдущий комментарий, тут останется только эта строка с условием на проверку существования контекста

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Context/Context.tsx
> +    setFrameCount(0)
зачем это нужно? выглядит бесполезно

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Context/Context.tsx
> +export const Canvas: FC<CanvasProps> = ({
компонент называется Canvas, а файл и папка Context, выбери одно название

2023-03-02 21:17 UTC, manshind commented on packages/client/src/components/Game/components/Context/Context.tsx
> +    if (isAnimating) {
как будто isAnimating бесполезный проп, без него вообще экран не будет обновляться

2023-03-02 21:20 UTC, manshind commented
Почини конфликты

2023-03-03 08:32 UTC, PlehanovEvgeniy commented on packages/client/src/hooks/useGameValue.tsx
> +export const useGameValue = () => {
Потому что хуки должны лежать в коре же, тк там может быть не только игровой хук

2023-03-05 11:26 UTC, PlehanovEvgeniy commented on packages/client/src/components/Game/common/allias.ts
> +export type Board = number[][];
Allias - псевдоним, использую для удобства и улучшения читабельности кода

2023-03-05 11:31 UTC, PlehanovEvgeniy commented on packages/client/src/components/Game/components/Text/Text.tsx
> +    context.font = 'bold 75px serif';
Canvas работает синхронно же, и если поместить это в юз ефект, то значения будут пропадать, будет только отрисовка

2023-03-05 11:32 UTC, PlehanovEvgeniy commented on packages/client/src/components/Game/components/RoundedRectangle/RoundedRectangle.tsx
> +      context.fillStyle = color
Комментарий выше

2023-03-05 11:38 UTC, PlehanovEvgeniy commented on packages/client/src/components/Game/components/Context/Context.tsx
> +  dpr: number;
Dpr - масштабирование, его можно использовать для анимации например в будущем, оно так и расшифровывается как dpr

2023-03-05 12:26 UTC, PlehanovEvgeniy commented on packages/client/src/components/Game/components/Context/Context.tsx
> +    context.clearRect(0, 0, actualWidth, actualHeight)
Да, чисткой занимает компонент контекст, т.к он отвечает за рендер всех компонентов. По правилам рендера перед обновлением кадра следует очистить окно рендера, что бы не было артифактов на экране.

2023-03-05 12:27 UTC, PlehanovEvgeniy commented on packages/client/src/components/Game/components/Context/Context.tsx
> +  const [context, setContext] = useState<CanvasRenderingContext2D>()
Это необходимо, что бы реакт делал перерендер в случае изменения контекста канваса

2023-03-05 12:27 UTC, PlehanovEvgeniy commented on packages/client/src/components/Game/components/Context/Context.tsx
> +    setFrameCount(0)
Необходимо для того, что бы задать стартовый индекс обновления окна

2023-03-05 12:56 UTC, manshind commented on packages/client/src/hooks/useGameValue.tsx
> +export const useGameValue = () => {
в коре желательно хранить только общие переиспользуемые хуки, иначе с жизнью проекта, эта директория разрастется и с ней будет неудобно работать.
Этот хук используется только в рамках игры

2023-03-05 12:58 UTC, manshind commented on packages/client/src/components/Game/common/allias.ts
> +export type Board = number[][];
это тип, а не псевдоним, лучше назвать файл types или definitions. Такое название лучше описывает, что в нем находится

2023-03-05 12:59 UTC, manshind commented on packages/client/src/components/Game/components/Text/Text.tsx
> +    context.font = 'bold 75px serif';
какие значения будут пропадать? у тебя от юз эффекта изменится только момент запуска твоего кода, все остальное должно работать так же, как и сейчас

2023-03-05 12:59 UTC, manshind commented on packages/client/src/components/Game/components/RoundedRectangle/RoundedRectangle.tsx
> +      context.fillStyle = color
ответил выше

2023-03-05 13:01 UTC, manshind commented on packages/client/src/components/Game/components/Context/Context.tsx
> +    context.clearRect(0, 0, actualWidth, actualHeight)
тогда убери очистку из Game.
И этот кусок кода надо сунуть в эффект

2023-03-05 13:03 UTC, manshind commented on packages/client/src/components/Game/components/Context/Context.tsx
> +  const [context, setContext] = useState<CanvasRenderingContext2D>()
для перерендера у тебя есть frameCount, а контекст канваса в твоем случае не меняется, так как сам элемент канваса один и тот же, тем более если и он изменится, то и контекст через обычную константу тоже обновится

2023-03-05 13:03 UTC, manshind commented on packages/client/src/components/Game/components/Context/Context.tsx
> +    setFrameCount(0)
чем для тебя это полезно? оно не выполняет никакой логики

2023-03-06 17:47 UTC, PlehanovEvgeniy commented on packages/client/src/components/Game/components/Tile/Tile.tsx
> +      <RoundedRectangle x={x} y={y} width={tileSize} height={tileSize} radius={5}
У нас пока не прокинут линтер

2023-03-07 10:58 UTC, manshind approved these changes

2023-03-07 10:58 UTC, manshind commented on packages/client/src/components/Game/common/direction.ts
> +export const directionByKey: { [key: string]: Direction } = {
Некритично. Для таких типов можешь использовать Record<string, Direction>

2023-03-07 10:58 UTC, manshind commented on packages/client/src/components/Game/common/types.ts
> +export type Board = number[][]
Сейчас у тебя получается немного странная ситуация. Ты вынес в коммон types, states и direction. Но по итогу у тебя в каждом из этих файлов лежат типы, из за чего теперь название types не полностью описывает что там лежит (типы находятся везде, но называешь типами только один файл, а не все).
Чтобы было понятнее я бы сделал следующее:

/common (или /types) (папка)
--/states (внутренний файл)
--/directions (внутренний файл)
--/board (внутренний файл)

2023-03-07 10:58 UTC, manshind commented on packages/client/src/components/Game/components/Board/Board.tsx
> +    const handleMove = (event: any) => {
Не указывай any. Описывай правильными типами

2023-03-07 10:58 UTC, manshind commented on packages/client/src/components/Game/components/Canvas/Canvas.tsx
> +    canvasContext.scale(dpr, dpr)
Это в эффект надо вынести

2023-03-08 17:44 UTC, ivee7 approved these changes

2023-03-09 10:46 UTC, merged