Kubik_16
twenty-forty-eight-kubiki/twenty-forty-eight pull request #9
Opened 2023-03-05 13:52 UTC by IvanB56

### Какую задачу решаем
Создание страницы leader bord, добавление api к странице

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-05 22:28 UTC, manshind requested changes
Запоминай, какие комменты оставляю, ошибки повторяются

2023-03-05 22:28 UTC, manshind commented on packages/client/src/App.tsx
> +      <LiederBoardPage />
Опечатка в названии

2023-03-05 22:28 UTC, manshind commented on packages/client/src/components/GamerItem/GamerItem.tsx
> +const GamerItem = (props: { profile: GamerItemProps }) => {
Выноси тип компонента отдельно выше объявления компонента, так у тебя уменьшается читаемость кода

2023-03-05 22:28 UTC, manshind commented on packages/client/src/pages/LiederBoardPage/LiederBoardPage.tsx
> +export interface GamerItemProps {
Этот интерфейс должен находиться в апи.
И переименуй его в LeadersResponse или как нибудь аналогично

2023-03-05 22:28 UTC, manshind commented on packages/client/src/api/leaderBoardApi.ts
> +  async getAll() {
Опиши возвращаемый тип

2023-03-05 22:28 UTC, manshind commented on packages/client/src/pages/LiederBoardPage/LiederBoardPage.tsx
> +        LeaderBoardApi.getAll().then();
Зачем тут пустой then?
Вероятно тут надо вызывать getLeaders

2023-03-05 22:28 UTC, manshind commented on packages/client/src/pages/LiederBoardPage/LiederBoardPage.tsx
> +        const response = LeaderBoardApi.getAll().then(response => response.json());
Почему опять смешиваешь async/await и обычные промисы? Выбери что нибудь одно

2023-03-05 22:28 UTC, manshind commented on packages/client/src/utils/baseURL.ts
> +export const BaseUrl = 'https://ya-praktikum.tech/api/v2';
Почему это в утилитах и с большой буквы?

2023-03-07 07:21 UTC, IvanB56 commented on packages/client/src/components/GamerItem/GamerItem.tsx
> +const GamerItem = (props: { profile: GamerItemProps }) => {
Можешь объяснить подробнее, не совсем понял что имеешь в виду?

2023-03-07 11:02 UTC, manshind commented on packages/client/src/components/GamerItem/GamerItem.tsx
> +const GamerItem = (props: { profile: GamerItemProps }) => {
interface GamerItemProps {
  profile: ...;
}

const GamerItem = (props: GamerItemProps) => {...}

Так ты визуально разделяешь пропсы и сам компонент, что даёт удобство при дальнейшем изменении или добавлении новых свойств в пропсы компонента

2023-03-07 11:08 UTC, manshind requested changes
Не залил исправления

2023-03-07 12:51 UTC, IvanB56 commented
Ошибки поправил, изменения залил

2023-03-07 17:28 UTC, manshind approved these changes
Ставлю заранее аппрув, но пробегись по новым комментариям. Если что то вызывает вопросы - пиши

2023-03-07 17:28 UTC, manshind commented on packages/client/src/api/leaderBoardApi.ts
> +export interface LeadersProps {
Тут ты описываешь не несколько сущностей, а одну. Поэтому тут должно быть LeaderProps.

И это некритично, но на будущее, старайся пропсами называть только то, что приходит в компонент. Иначе с первого взгляда тяжело понять что это такое и кажется, что это какие то пропсы компонента. Стоит назвать LeaderResponse или как нибудь аналогично

2023-03-07 17:28 UTC, manshind commented on packages/client/src/api/leaderBoardApi.ts
> +  async getAll(): Promise<LeadersProps[] | LeadersError> {
В типах промисов ошибка не описывается, должен быть указан только тип успешного ответа.
Тип ошибки указывается в каждом блоке catch.

2023-03-07 17:28 UTC, manshind commented on packages/client/src/pages/LeaderBoardPage/LeaderBoardPage.scss
> +.lieder-board-page {
Опечатка

2023-03-07 17:28 UTC, manshind commented on packages/client/src/pages/LeaderBoardPage/LeaderBoardPage.tsx
> +  const [leaders, setLeaders] = useState<LeadersProps[] | LeadersError>([])
Тут не будет ошибки, нужно убрать ее из типа

2023-03-07 17:28 UTC, manshind commented on packages/client/src/components/GamerItem/GamerItem.tsx
> +import { LeadersProps } from '../../pages/LeaderBoardPage/LeaderBoardPage'
В этом компоненте нет такого экспорта, ее надо тянуть из api. В консоли должны были быть ошибки, следи за ними внимательно

2023-03-08 17:44 UTC, ivee7 approved these changes

2023-03-09 07:03 UTC, merged